// Code generated by "go-wrap"; DO NOT EDIT.
package generator

import (
	"text/template"

	"github.com/catmorte/go-wrap/internal/declaration"
	. "github.com/catmorte/go-wrap/pkg/wrap"
)

func getWrapPrefixWrap(arg0 []*declaration.Import) Out[string] {
	return OK(getWrapPrefix(arg0))
}

func parseTemplateWrap() Out[*template.Template] {
	return Wrap(parseTemplate())
}

func executeTemplateWrap[T any](arg0 *template.Template, arg1 T) Out[[]byte] {
	return Wrap(executeTemplate(arg0, arg1))
}

func newFileTemplateDataWrap(arg0 string, arg1 string, arg2 declaration.File, arg3 bool) Out[fileTemplateData] {
	return OK(newFileTemplateData(arg0, arg1, arg2, arg3))
}

func formatSourceWrap(arg0 []byte) Out[[]byte] {
	return Wrap(formatSource(arg0))
}

func formatImportsWrap(arg0 []byte) Out[[]byte] {
	return Wrap(formatImports(arg0))
}
